In [1]:
print("se otepavme ama uspea")

se otepavme ama uspea


In [3]:
import pandas as pd 

In [104]:
person = {
    "name" : "Nat",
    "surname" : "G",
    "embg" : "211526",
    "age" : 22,
    "height" : 164.5
}

In [4]:
data = pd.read_csv('Desktop/vnp/podatoci')

FileNotFoundError: [Errno 2] No such file or directory: 'Desktop/vnp/podatoci'

In [7]:
integer_var=15


In [8]:
print(integer_var)

15


In [9]:
string_var="Hello world"

In [10]:
float_var=42.5
bool_var=True


In [11]:
print(string_var)

Hello world


In [12]:
print(float_var)

42.5


In [13]:
print(bool_var)

True


In [14]:
print(integer_var)

15


In [15]:
print(integer_var, string_var, float_var)

15 Hello world 42.5


In [16]:
string1="Hello"

In [17]:
string2='Vtoro'

In [18]:
string1
string2

'Vtoro'

In [19]:
string1

'Hello'

Checking variable types and casting

In [20]:
print(type(string1))

<class 'str'>


String are classes (derived types), integers and floats are primitive types

In [21]:
type(integer_var), type(float_var)

(int, float)

In [23]:
print(float_var)
float_var

42.5


42.5

In [24]:
int(float_var)

42

In [25]:
integer_var

15

In [26]:
print(integer_var)

15


In [27]:
str(integer_var)

'15'

In [28]:
x,y,z="test", 1, 65.33

**0. Conditions**

In [30]:
if integer_var < 20:
    print("the variable is less than 20")


the variable is less than 20


In [34]:
if integer_var < 10:
    print("the variable is less than 10")

In [36]:
if integer_var < 10:
    print("the variable is less than 10")
else:
    print("the variable is greater than or equal to 10")

the variable is greater than or equal to 10


In [39]:
if integer_var < 10:
    print("the variable is less than 10")
elif integer_var <= 15:
    print("the variable is less than or equal to 15")
else:
    print("the variable is greater than 15")

the variable is less than or equal to 15


**1. Ranges:**

In [48]:
same_type_list=[1,5,7, 3432, 123]

In [41]:
different_type_list=[53, 556.23, "hello"]

In [42]:
print(different_type_list)

[53, 556.23, 'hello']


In [43]:
print(same_type_list)

[1, 5, 10, 456]


In [49]:
same_type_list[1:-1]

[5, 7, 3432]

In [50]:
same_type_list[1:4]

[5, 7, 3432]

In [51]:
same_type_list[0:-1]

[1, 5, 7, 3432]

In [52]:
same_type_list[0:4]

[1, 5, 7, 3432]

In [53]:
same_type_list[0:5]

[1, 5, 7, 3432, 123]

In [54]:
same_type_list[0:-0]

[]

In [55]:
same_type_list[-1]

123

In [56]:
same_type_list[0:-1]

[1, 5, 7, 3432]

**2. List comprehension**

**Lists are ordered, changeable, indexed and allow duplicates**

In [59]:
new_list = [element for element in same_type_list if element > 10]

**Gi zema site brojki koi se nad 10 od listata same_type_list**

In [61]:
new_list

[3432, 123]

**3. Tuples**

**Tuples are ordered and unchangeable. You cannot change, add or remove items**

**Tuples allow duplicates**

In [74]:
tuple1= (1,2,3,4)
tuple2= (5, "abc", 45356.566)

In [69]:
tuple1[0]

1

In [70]:
tuple2[0] = "test"

TypeError: 'tuple' object does not support item assignment

**We can just initialize new tuples, and insert values accordingly**

In [71]:
newTuple = ("test",) + tuple2[1:]

In [72]:
newTuple

('test', 'abc', 45356.566)

**4.Sets**

**Sets are unordered, unchangeable, unindexed and do not allow duplicate values**

**You cannot change its items, but you can add and remove items**

In [77]:
fruit_set = {"apple", "banana", "orange", "apple"}

In [78]:
fruit_set

{'apple', 'banana', 'orange'}

In [79]:
fruit_set.add("banana")

In [80]:
fruit_set

{'apple', 'banana', 'orange'}

In [81]:
fruit_set.add("malinki")

In [82]:
fruit_set

{'apple', 'banana', 'malinki', 'orange'}

In [83]:
fruit_set[0]

TypeError: 'set' object is not subscriptable

**5. Dictionaries and Files**

**Dictionaries are ordered, changeable, but do not allow duplicates**

In [104]:
person = {
    "name" : "Nat",
    "surname" : "G",
    "embg" : "211526",
    "age" : 22,
    "height" : 164.5
}

In [89]:
print(person)

{'name': 'Nat', 'surname': 'G', 'embg': '211526', 'age': 22, 'height': 164.5}


In [90]:
print(person["name"])

Nat


In [91]:
person["name"]

'Nat'

In [92]:
person.keys

<function dict.keys>

In [93]:
person.keys()

dict_keys(['name', 'surname', 'embg', 'age', 'height'])

In [94]:
print(person.keys())

dict_keys(['name', 'surname', 'embg', 'age', 'height'])


In [95]:
def pechatenjeRechnik(dict_object):
    for k in dict_object.keys():
        print(k, "-->", dict_object[k])

**dodavanje na nov element vo rechnikot**

In [96]:
person["is_student"]=True

In [97]:
print(person)

{'name': 'Nat', 'surname': 'G', 'embg': '211526', 'age': 22, 'height': 164.5, 'is_student': True}


In [98]:
pechatenjeRechnik(person)

name --> Nat
surname --> G
embg --> 211526
age --> 22
height --> 164.5
is_student --> True


**dodavanje na lista vo rechnik**

In [100]:
coursesList = ["Data Science", "Business", "Web Development"]

In [101]:
person["teaches"] = coursesList

In [103]:
pechatenjeRechnik(person)

name --> Nat
surname --> G
embg --> 211526
age --> 22
height --> 164.5
is_student --> True
teaches --> ['Data Science', 'Business', 'Web Development']


In [108]:
carDict = { 
    "make" : "Lambo",
    "model" : "Aven",
    "hp" : 1000,
}

In [109]:
person["car"] = carDict

In [110]:
pechatenjeRechnik(person)

name --> Nat
surname --> G
embg --> 211526
age --> 22
height --> 164.5
car --> {'make': 'Lambo', 'model': 'Aven', 'hp': 1000}


**vadenje na element od rechnik**

In [111]:
person.pop("car")

{'make': 'Lambo', 'model': 'Aven', 'hp': 1000}

In [112]:
pechatenjeRechnik(person)

name --> Nat
surname --> G
embg --> 211526
age --> 22
height --> 164.5


In [114]:
print(person)

{'name': 'Nat', 'surname': 'G', 'embg': '211526', 'age': 22, 'height': 164.5}


In [115]:
person["car"] = carDict

In [116]:
print(person)

{'name': 'Nat', 'surname': 'G', 'embg': '211526', 'age': 22, 'height': 164.5, 'car': {'make': 'Lambo', 'model': 'Aven', 'hp': 1000}}


In [117]:
pechatenjeRechnik(person)

name --> Nat
surname --> G
embg --> 211526
age --> 22
height --> 164.5
car --> {'make': 'Lambo', 'model': 'Aven', 'hp': 1000}


In [118]:
person["teaches"] = coursesList

In [119]:
pechatenjeRechnik(person)

name --> Nat
surname --> G
embg --> 211526
age --> 22
height --> 164.5
car --> {'make': 'Lambo', 'model': 'Aven', 'hp': 1000}
teaches --> ['Data Science', 'Business', 'Web Development']


In [120]:
person["is_student"]=True

In [121]:
pechatenjeRechnik(person)

name --> Nat
surname --> G
embg --> 211526
age --> 22
height --> 164.5
car --> {'make': 'Lambo', 'model': 'Aven', 'hp': 1000}
teaches --> ['Data Science', 'Business', 'Web Development']
is_student --> True


**6. Numpy and Pandas**

**NumPy is a Python library used for working with arrays**

In [124]:
import numpy as np
import pandas as pd

In [126]:
niza = np.array([1,2,5,6])

In [127]:
niza

array([1, 2, 5, 6])

In [128]:
nizaMixed = np.array([1,2,24.4,6,"test"])

**dtype indicira kakov tip na elementi se vo NumPy**

**When creating a NumPy array, all elements must be of the same type. Since the array nizaMixed includes a mix of integers, a float and a string, NumPy automatically converts all elements to strings to keep the data type consistent in the array**

In [129]:
nizaMixed

array(['1', '2', '24.4', '6', 'test'], dtype='<U32')

In [130]:
nizaMixed

['1' '2' '24.4' '6' 'test']


**.ndim returns the number of dimensions of the array**

In [133]:
nizaMixed.ndim

1

**.shape returns dimensions of the array as a tuple.**

**nizaMixed is a 1 dimensional array with 5 elements**

In [134]:
nizaMixed.shape

(5,)

**7. 2d arrays**

In [137]:
matrica = np.array ([
    [1,5,6,7],
    [2,4,2,2],
])

In [138]:
matrica

array([[1, 5, 6, 7],
       [2, 4, 2, 2]])

In [139]:
print(matrica)

[[1 5 6 7]
 [2 4 2 2]]


In [140]:
matrica.shape

(2, 4)

In [141]:
matrica.ndim

2

In [143]:
niza

array([1, 2, 5, 6])

In [144]:
matrica

array([[1, 5, 6, 7],
       [2, 4, 2, 2]])

**niza+matrica ke ja soberi nizata so sekoja dimenzija na matricata**

In [145]:
niza + matrica

array([[ 2,  7, 11, 13],
       [ 3,  6,  7,  8]])

**8. Pandas DataFrames**

In [146]:
dataDict = {
    "index" : [1235, 43534, 43253, 54353],
    "name" : ["Nat", "Marija", "Angela", "Evgenija"],
    "grade" : [5,6,7,8]
}

In [147]:
print(dataDict)

{'index': [1235, 43534, 43253, 54353], 'name': ['Nat', 'Marija', 'Angela', 'Evgenija'], 'grade': [5, 6, 7, 8]}


In [148]:
dataDict

{'index': [1235, 43534, 43253, 54353],
 'name': ['Nat', 'Marija', 'Angela', 'Evgenija'],
 'grade': [5, 6, 7, 8]}

**Takes the dictionary and converts it into a table**

In [149]:
df = pd.DataFrame(dataDict)

In [150]:
df

index      name  grade
0   1235       Nat      5
1  43534    Marija      6
2  43253    Angela      7
3  54353  Evgenija      8

In [151]:
print(df)

   index      name  grade
0   1235       Nat      5
1  43534    Marija      6
2  43253    Angela      7
3  54353  Evgenija      8


In [152]:
df.to_csv('grades.csv')